services:

  # Web Server Service
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - php


  # Application Service
  php:
    image: php:8.3-fpm
    container_name: php
    volumes:
      - ./:/var/www

  #Database Service
#  db:


