services:

  # Web Server Service
  nginx:
    image: nginx:latest
    container_name: project-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app


  # Application Service
  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    container_name: project-php
    volumes:
      - ./:/var/www

  #Database Service
#  db:


